### PR TITLE
Row major

### PR DESCRIPTION
**Pull request by alvarohm**

### CODE REVIEW

**Comment by alvarohm** [comment]
I'm not sure why this is running against an older version of the tests. Maybe cache? Will try to fix later.

**Comment by pefribeiro** [comment]
I can fix that, just a second.

**Comment by pefribeiro** [comment]
@alvarohm, I think there is a genuine issue. The second issue is that the assertion is running in both timed/untimed versions, but the process is only defined untimed.

**Comment by pefribeiro** [comment]
The first issue is perhaps due to the runner not clearing the submodule folder when checking out. I don't think the file 'test_assertions.assertions' should exist at all. I'll look into that.

**Comment by alvarohm** [comment]
No, it doesn't look like it should. Before it was checking
check1.assertios, which had already been renamed.

**Comment by pefribeiro** [comment]
Just noting here for posterity the reason this was throwing problems when compiling on the server. Basically the GitHub checkout action doesn't properly clean the submodule in `robochart-tests`. For some reason `git clean -xffd` is not enough, on its own, to clean submodules, [although it should](https://git-scm.com/docs/git-clean). In commit 7307b47 I've extended the script to apply `git submodule foreach --recursive git clean -xffd`. There is an open [pull-request to fix the action](https://github.com/actions/checkout/pull/628). If it ever gets merged we can simplify the yml.

Similar fix should be deployed to the build of https://github.com/UoY-RoboStar/robosim-csp-gen.

**Pull request closed without merging**
